apiVersion: apps/v1
kind: Deployment
metadata:
  name: bancodigital
  labels:
    app: bancodigital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bancodigital
  template:
    metadata:
      labels:
        app: bancodigital
    spec:
      containers:
        - name: bancodigital
          image: bancodigital:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: SPRING_DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: DATASOURCE_PASSWORD
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: APP_JWT_SECRET
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: SPRING_MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: SPRING_MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bancodigital-secrets
                  key: SPRING_MAIL_PASSWORD
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: "bancodigital"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
